version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: support_app
    ports:
      - "3000:3000"   # client portal
      - "3003:3003"   # internal portal
      - "4000:4000"   # API
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=supportdb
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:15
    container_name: support_db
    restart: always
    environment:
      POSTGRES_DB: supportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - support_pgdata:/var/lib/postgresql/data

volumes:
  support_pgdata:

